bot/urls.py
"""Defines URL patterns for bot."""
from django.urls import path
from . import views

app_name = 'bot'
urlpatterns = [
    # Run bot
    # path('run-bot/', views.run_bot, name='run-bot'),
    # Bot Report Page
    path('bot-report/<int:pk>/', views.BotReport.as_view(), name='bot-report'),
    # Bot Reports Page
    path('bot-reports/', views.BotReportsView.as_view(), name='bot-reports'),
    # Edit Bot Report Page
    path('bot-edit-rental-prop-calc/<int:pk>/', views.bot_edit_rental_prop_calc, name='bot-edit-rental-prop-calc'),
    # Delete Bot Report Page
    path('bot-delete-report/<int:pk>/', views.bot_delete_report, name='bot-delete-report'),
    # Bot PDF report 
    path('bot-pdf-report/<int:pk>/', views.ViewBotReportPDF.as_view(), name='bot-pdf-report'),
]

rentalcalc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings #add this
from django.conf.urls.static import static #add this

urlpatterns = [
    path('', include('calculator.urls')),
    path('users/', include('users.urls')),
    path('bot/', include('bot.urls')),
    path('admin/', admin.site.urls),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bot/models.py
# Django imports
from django.db import models
from django.contrib.auth.models import User

# My file imports
from calculator.choices import *


class BotRentalReport(models.Model):
    """A rental property report the user would like to create"""
    created_at              = models.DateTimeField(auto_now_add=True)
    updated_at              = models.DateTimeField(auto_now=True)
    owner                   = models.ForeignKey(User, on_delete=models.CASCADE, \
                                blank=True, null=True)
    bot_generated           = models.BooleanField(default=True)
    # quality of investment
    quality_g               = models.BooleanField(blank=True, default=False)
    quality_a               = models.BooleanField(blank=True, default=False)
    quality_b               = models.BooleanField(blank=True, default=False)

    # Property Info
    report_title            = models.CharField(max_length=75)
    owned                   = models.BooleanField(blank=True)
    prop_address            = models.CharField(max_length=75, blank=True)
    prop_city               = models.CharField(max_length=50, blank=True)
    prop_state              = models.CharField(max_length=25, blank=True)
    prop_zip                = models.CharField(max_length=10, blank=True, \
                                verbose_name='Zip')
    bedrooms                = models.CharField(max_length=10, \
                                choices=BEDROOMS, default='', blank=True)
    bathrooms               = models.CharField(max_length=10, \
                                choices=BATHROOMS, default='', blank=True)
    sqft                    = models.CharField(max_length=30, blank=True)
    year_built              = models.CharField(max_length=4, blank=True)
    prop_description        = models.TextField(blank=True)
    prop_photo              = models.ImageField(upload_to='property_photos', blank=True)
    prop_mls                = models.CharField(max_length=30, blank=True)
    
    # Purchase Info 
    purchase_price          = models.IntegerField()
    purchase_closing_cost   = models.IntegerField()
    est_repair_cost         = models.IntegerField(blank=True, null=True)
    after_repair_value      = models.IntegerField(blank=True, null=True)
    annual_pv_growth        = models.DecimalField(max_digits=4, decimal_places=2, \
                                blank=True, null=True, default=2)

    # Loan Details
    cash_purchase           = models.BooleanField(blank=True, default=False)
    down_payment            = models.CharField(max_length=10, \
                                choices=DOWN_PMT_PERCENT, default='', blank=True)
    down_payment_2          = models.IntegerField(blank=True, null=True)
    loan_int_rate           = models.DecimalField(max_digits=5, decimal_places=3)
    points                  = models.SmallIntegerField(blank=True, null=True)
    loan_term               = models.SmallIntegerField()

    # Rental Income
    gross_monthly_rent      = models.SmallIntegerField() 
    other_monthly_income    = models.SmallIntegerField(blank=True, null=True)
    annual_income_growth    = models.DecimalField(max_digits=4, decimal_places=2, \
                                blank=True, null=True, default=2)

    # Expenses
    prop_annual_taxes       = models.IntegerField()
    monthly_insurance       = models.DecimalField(max_digits=7, decimal_places=2)
    repairs_maint           = models.DecimalField(max_digits=4, decimal_places=2, \
                                blank=True, null=True)
    vacancy                 = models.DecimalField(max_digits=4, decimal_places=2, \
                                blank=True, null=True)
    cap_expenditures        = models.DecimalField(max_digits=4, decimal_places=2, \
                                blank=True, null=True)
    mgmt_fees               = models.DecimalField(max_digits=4, decimal_places=2, \
                                blank=True, null=True)
    electricity             = models.DecimalField(max_digits=7, decimal_places=2, \
                                blank=True, null=True)
    gas                     = models.DecimalField(max_digits=7, decimal_places=2, \
                                blank=True, null=True)
    water_sewer             = models.DecimalField(max_digits=7, decimal_places=2, \
                                blank=True, null=True)
    hoa                     = models.DecimalField(max_digits=7, decimal_places=2, \
                                blank=True, null=True)
    garbage                 = models.DecimalField(max_digits=7, decimal_places=2, \
                                blank=True, null=True)
    pmi                     = models.DecimalField(max_digits=7, decimal_places=2, \
                                blank=True, null=True)
    other_monthly_expenses  = models.DecimalField(max_digits=7, decimal_places=2, \
                                blank=True, null=True)
    annual_expenses_growth  = models.DecimalField(max_digits=4, decimal_places=2, \
                                blank=True, null=True, default=2)
    sales_expenses          = models.DecimalField(max_digits=4, decimal_places=2, \
                                blank=True, null=True, default=7.5)

    # scrape details
    redfin_listing_url      = models.URLField(blank=True)   
    zillow_zestimate_url    = models.URLField(blank=True)

    def __str__(self):
        """Return a string representation of the model."""
        return self.report_title + ' - ' + self.owner.username + f' ({str(self.id)})'

    def save(self, *args, **kwargs):
        """Saves model. Sets ARV equal to purchase price if ARV is blank"""
        if self.after_repair_value == None:
            self.after_repair_value = self.purchase_price
        super(BotRentalReport, self).save(*args, **kwargs)

bot/forms.py
# Django imports
from django import forms

# My file imports
from .models import *

class BotRentalPropForm(forms.ModelForm):
    """Form for bot calculator"""
    required_css_class = 'required'
    class Meta:
        model = BotRentalReport
        fields = '__all__'
        widgets = {'owner': forms.HiddenInput()}

bot/views.py
# Django imports
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import Http404
from django.views.generic import ListView, View

# My file imports
from bot.forms import BotRentalPropForm
from .utils import CreatePdfMixin, ProcessReportMixin
from .models import BotRentalReport
from calculator.models import UserSettings


# @login_required
# def run_bot(request):
#     """Runs bot"""
#     run_bot_logic(request.user)
#     return redirect('bot:bot-reports')
    
@method_decorator(login_required, name='dispatch')
class BotReport(ProcessReportMixin, View):
    """The bot report page"""
    model = BotRentalReport
    template = 'bot/bot_report.html'

@method_decorator(login_required, name='dispatch')
class BotReportsView(ListView):
    """Page for listing all bot reports"""
    model = BotRentalReport
    template_name = 'bot/bot_reports.html'
    paginate_by = 6
    context_object_name = 'bot_object_list'

    def get_queryset(self):
        return BotRentalReport.objects.filter(owner=self.request.user).order_by('-created_at')

@login_required
def bot_delete_report(request, pk):
    """Delete report"""
    try:
        report = BotRentalReport.objects.get(id=pk)
    except:
        raise Http404
    if report.owner != request.user:
        raise Http404

    usr_settings = UserSettings.objects.get(user=request.user)

    # checks for blacklist setting = True. addresses, adds address is 
    if getattr(usr_settings, 'blacklist_bool'):
        addr = getattr(report, 'prop_address')
        city = getattr(report, 'prop_city')
        state = getattr(report, 'prop_state')
        zipcode = getattr(report, 'prop_zip')

        current_json = getattr(usr_settings, 'addr_blacklist')

        if not f'{addr} {city}, {state} {zipcode}' in \
            current_json[request.user.username]['addresses']:
            new_json = current_json[request.user.username]['addresses']
            new_json.append(f'{addr} {city}, {state} {zipcode}')
        else: 
            new_json = current_json[request.user.username]['addresses']

        # updates blacklisted addresses if any. creates if none
        obj, _ = UserSettings.objects.update_or_create(
            user=request.user,
            defaults={'addr_blacklist': {
                    request.user.username: {
                        'addresses': new_json,
                    }
                } 
            }
        )

    report.delete()
    return redirect('bot:bot-reports')

@login_required
def bot_edit_rental_prop_calc(request, pk):
    """Edit a report"""
    try:
        item = BotRentalReport.objects.get(id=pk)
    except:
        raise Http404
    if item.owner != request.user:
        raise Http404
    if request.method == 'POST':
        # POST data submitted; process data.
        form = BotRentalPropForm(request.POST, request.FILES, instance=item)
        if form.is_valid():
            form.save()
            return redirect(f'/bot/bot-report/{pk}')

    else:
        # Initial request; pre-fill form with the current entry.
        form = BotRentalPropForm(instance=item)

    # Display a blank or invalid form.
    context = {'item': item,'form': form}
    return render(request, 'bot/bot_calculator.html', context)

@method_decorator(login_required, name='dispatch')
class ViewBotReportPDF(CreatePdfMixin, View):
    """Renders PDF of report data"""
    model = BotRentalReport
    template = 'calculator/report_pdf.html'

bot/templates/bot/bot_reports.html
{% extends "calculator/base.html" %}
{% load tz %}
{% load static %}

{% block page_header %}
<div>
  <h1 class="pageTitle text-center py-4">Bot Reports</h1>
</div>

{% endblock page_header %}

{% block content %}
<div class="">
  <div class="row align-items-start text-dark rounded py-2 my-3 bg-secondary bg-opacity-10">
    <div class="col-1">
    </div>
    <div class="col-3">
      Report Name
    </div>
    <div class="col-3">
      Address
    </div>
    <div class="col-1">
      Created
    </div>
    <div class="col-1">
      Updated
    </div>
    <div class="col-1">
      Quality
    </div>
    <div class="col-1">
    </div>
    <div class="col-1">
    </div>
  </div>
</div>

<div>

{% if bot_object_list %}
    <ul class="reportList">
        {% for report in  bot_object_list %}
        <li>
            <div class="reportRow row align-items-start my-2 bg-white border rounded">
                <div class="col-1 reportImageContainer align-self-center">
                    <a href="{% url 'bot:bot-report' report.id %}">
                        {% if report.prop_photo %}
                            <img src="{{ report.prop_photo.url }}" class="img-fluid">
                        {% endif %}
                    </a>
                </div>
                <div class="col-3 align-self-center reportTitle">
                    <a href="{% url 'bot:bot-report' report.id %}">
                        {{ report.report_title }}
                    </a>
                </div>
                <div class="col-3 text-muted align-self-center">
                    {% if report.prop_address %}
                        <p class="card-text">{{ report.prop_address }}, {{ report.prop_city }}, {{ report.prop_state }} {{ report.prop_zip }}</p>
                    {% endif %}
                </div>
                <div class="col-1 text-muted align-self-center">
                    {% timezone "America/New_York" %}
                        {{ report.created_at|date:"M j 'y" }}
                    {% endtimezone %}
                </div>
                <div class="col-1 text-muted align-self-center">
                    {% timezone "America/New_York" %}
                        {{ report.updated_at|date:"M j 'y" }}
                    {% endtimezone %}
                </div>
                <div class="col-1 text-muted align-self-center">
                    {% if report.quality_g %}
                        &#128077
                    {% elif report.quality_b %}
                        &#128078
                    {% elif report.quality_a %}
                        &#129335
                    {% endif %}
                </div>
                <div class="col-1 align-self-center">
                    <a class="btn btn-secondary" href="{% url 'bot:bot-edit-rental-prop-calc' report.pk %}">
                        Edit
                    </a>
                </div>
                <div class="col-1 editDeleteButtons align-self-center">
                    <a class="modalLink btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal">
                        X
                    </a>
                </div>
                {% include "calculator/modal.html" %}
            </div> 
        </li>
        {% endfor %}
    </ul>

        {% if is_paginated %}
            <nav aria-label="Page navigation">
                <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">PREV</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link">PREV</a>
                        </li>
                    {% endif %}
                    {% with ''|center:page_obj.paginator.num_pages as range %}
                        {% for _ in range %}
                        {% if page_obj.number == forloop.counter %}
                            <li class="page-item page-item-num active" id="paginator_{{ forloop.counter }}"><a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
                        {% else %}
                            <li class="page-item page-item-num" id="paginator_{{ forloop.counter }}"><a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
                        {% endif %}
                        {% endfor %}
                    {% endwith %}
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">NEXT</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link">NEXT</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}

  {% else %}
     <div class="text-center">No bot reports here yet</div>
  {% endif %}

  
  
</div>

{% endblock content %}