bot/urls.py
"""Defines URL patterns for bot."""
from django.urls import path
from . import views

app_name = 'bot'
urlpatterns = [
    # Run bot
    # path('run-bot/', views.run_bot, name='run-bot'),
    # Bot Report Page
    path('bot-report/<int:pk>/', views.BotReport.as_view(), name='bot-report'),
    # Bot Reports Page
    path('bot-reports/', views.BotReportsView.as_view(), name='bot-reports'),
    # Edit Bot Report Page
    path('bot-edit-rental-prop-calc/<int:pk>/', views.bot_edit_rental_prop_calc, name='bot-edit-rental-prop-calc'),
    # Delete Bot Report Page
    path('bot-delete-report/<int:pk>/', views.bot_delete_report, name='bot-delete-report'),
    # Bot PDF report 
    path('bot-pdf-report/<int:pk>/', views.ViewBotReportPDF.as_view(), name='bot-pdf-report'),
]

calculator/urls.py
"""Defines URL patterns for calculator."""
from django.urls import path
from . import views

app_name = 'calculator'
urlpatterns = [
    # Home Page
    path('', views.index, name='index'),
    # Dashboard Page
    path('dashboard/', views.dashboard, name='dashboard'),
    # Reports Page
    path('reports/', views.ReportsView.as_view(), name='reports'),
    # Calculator Page
    path('rental-prop-calculator/', views.rental_prop_calculator, name='rental-prop-calculator'),
    # Report Page
    path('report/<int:pk>/', views.Report.as_view(), name='report'),
    # Edit Report Page
    path('edit-rental-prop-calc/<int:pk>/', views.edit_rental_prop_calc, name='edit-rental-prop-calc'),
    # Delete Report Page
    path('delete-report/<int:pk>/', views.delete_report, name='delete-report'),
    # PDF report 
    path('pdf-report/<int:pk>/', views.ViewReportPDF.as_view(), name='pdf-report'),
    # User Settings Page
    path('settings/', views.settings, name='settings'),
]

rentalcalc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings #add this
from django.conf.urls.static import static #add this

urlpatterns = [
    path('', include('calculator.urls')),
    path('users/', include('users.urls')),
    path('bot/', include('bot.urls')),
    path('admin/', admin.site.urls),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
"""Defines URL patterns for users."""
from django.urls import path, include
from . import views


app_name = 'users'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
    
]

calculator/models.py
# Django imports
from django.db import models
from django.contrib.auth.models import User

# 3rd party imports
from multiselectfield import MultiSelectField

# My file imports
from .choices import *

class UserSettings(models.Model):
    """Model for storing user calculator and bot settings"""
    user                = models.OneToOneField(User, on_delete=models.CASCADE, related_name='settings')

    # Calculator Settings
    down_payment        = models.CharField(max_length=10, \
                                choices=DOWN_PMT_PERCENT, default='', blank=True)
    loan_int_rate       = models.DecimalField(max_digits=5, decimal_places=3, \
                            blank=True, null=True)
    loan_term           = models.SmallIntegerField(blank=True, null=True)
    repairs_maint       = models.DecimalField(max_digits=4, decimal_places=2, \
                            blank=True, null=True)
    vacancy             = models.DecimalField(max_digits=4, decimal_places=2, \
                            blank=True, null=True)
    cap_expenditures    = models.DecimalField(max_digits=4, decimal_places=2, \
                            blank=True, null=True)
    mgmt_fees           = models.DecimalField(max_digits=4, decimal_places=2, \
                            blank=True, null=True)

    # Investment Quality Settings
    coc_roi_bottom      = models.DecimalField(max_digits=4, decimal_places=2, \
                            blank=True, null=True)
    coc_roi_top         = models.DecimalField(max_digits=4, decimal_places=2, \
                            blank=True, null=True)
    cashflow_bottom      = models.SmallIntegerField(blank=True, null=True)
    cashflow_top         = models.SmallIntegerField(blank=True, null=True)

    # Bot Settings
    city                = models.CharField(max_length=30, blank=True)
    state               = models.CharField(max_length=10, \
                                choices=STATES, default='', blank=True)
    city_code           = models.CharField(max_length=10, blank=True)                       
    minor_civil_div     = models.BooleanField(blank=True, default=False)
    zipcode             = models.CharField(max_length=5, blank=True)

    # Bot Filters
    min_price           = models.CharField(max_length=10, \
                                choices=BOT_MIN_PRICE, default='', blank=True)
    max_price           = models.CharField(max_length=10, \
                                choices=BOT_MAX_PRICE, default='', blank=True)
    prop_type           = MultiSelectField(max_length=100, \
                                choices=PROPERTY_TYPES, default=None, blank=True)
    min_beds            = models.CharField(max_length=10, \
                                choices=BOT_MIN_BEDS, default='', blank=True)
    max_beds            = models.CharField(max_length=10, \
                                choices=BOT_MAX_BEDS, default='', blank=True)
    min_baths           = models.CharField(max_length=10, \
                                choices=BOT_MIN_BATHS, default='', blank=True)

    # Bot Schedule
    bot_frequency       = models.CharField(max_length=100, \
                                choices=BOT_FREQUENCY, default='', blank=True)

    # Address Blacklist
    blacklist_bool      = models.BooleanField(blank=True, default=False)
    addr_blacklist      = models.JSONField(blank=True, default=dict)

    def __str__(self):
        """Return a string representation of the model"""
        return f'{self.user}' + ' settings'

    def save(self, *args, **kwargs):
        """Saves model"""
        if self.city and self.city_code and self.state:
            self.zipcode = ''
        if self.zipcode:
            self.city = ''
            self.city_code = '' 
            self.state = ''
        super(UserSettings, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = "User Settings"


class RentalPropCalcReport(models.Model):
    """A rental property report the user would like to create"""
    created_at              = models.DateTimeField(auto_now_add=True)
    updated_at              = models.DateTimeField(auto_now=True)
    owner                   = models.ForeignKey(User, on_delete=models.CASCADE, \
                                blank=True, null=True)
    # quality of investment
    quality_g               = models.BooleanField(blank=True, default=False)
    quality_a               = models.BooleanField(blank=True, default=False)
    quality_b               = models.BooleanField(blank=True, default=False)

    # Property Info
    listing_url             = models.URLField(blank=True)
    report_title            = models.CharField(max_length=75)
    owned                   = models.BooleanField(blank=True)
    prop_address            = models.CharField(max_length=75, blank=True)
    prop_city               = models.CharField(max_length=50, blank=True)
    prop_state              = models.CharField(max_length=10, \
                                choices=STATES, default='', blank=True)
    prop_zip                = models.CharField(max_length=10, blank=True, \
                                verbose_name='Zip')
    bedrooms                = models.CharField(max_length=10, \
                                choices=BEDROOMS, default='', blank=True)
    bathrooms               = models.CharField(max_length=10, \
                                choices=BATHROOMS, default='', blank=True)
    sqft                    = models.CharField(max_length=30, blank=True)
    year_built              = models.CharField(max_length=4, blank=True)
    prop_description        = models.TextField(blank=True)
    prop_photo              = models.ImageField(upload_to='property_photos', blank=True)
    prop_mls                = models.CharField(max_length=30, blank=True)
    
    # Purchase Info 
    purchase_price          = models.IntegerField()
    purchase_closing_cost   = models.IntegerField()
    est_repair_cost         = models.IntegerField(blank=True, null=True)
    after_repair_value      = models.IntegerField(blank=True, null=True)
    annual_pv_growth        = models.DecimalField(max_digits=4, decimal_places=2, \
                                blank=True, null=True, default=2)

    # Loan Details
    cash_purchase           = models.BooleanField(blank=True)
    down_payment            = models.CharField(max_length=10, \
                                choices=DOWN_PMT_PERCENT, default='', blank=True)
    down_payment_2          = models.IntegerField(blank=True, null=True)
    loan_int_rate           = models.DecimalField(max_digits=5, decimal_places=3)
    points                  = models.SmallIntegerField(blank=True, null=True)
    loan_term               = models.SmallIntegerField()

    # Rental Income
    gross_monthly_rent      = models.SmallIntegerField()
    other_monthly_income    = models.SmallIntegerField(blank=True, null=True)
    annual_income_growth    = models.DecimalField(max_digits=4, decimal_places=2, \
                                blank=True, null=True, default=2)

    # Expenses
    prop_annual_taxes       = models.IntegerField()
    monthly_insurance       = models.DecimalField(max_digits=7, decimal_places=2)
    repairs_maint           = models.DecimalField(max_digits=4, decimal_places=2, \
                                blank=True, null=True)
    vacancy                 = models.DecimalField(max_digits=4, decimal_places=2, \
                                blank=True, null=True)
    cap_expenditures        = models.DecimalField(max_digits=4, decimal_places=2, \
                                blank=True, null=True)
    mgmt_fees               = models.DecimalField(max_digits=4, decimal_places=2, \
                                blank=True, null=True)
    electricity             = models.DecimalField(max_digits=7, decimal_places=2, \
                                blank=True, null=True)
    gas                     = models.DecimalField(max_digits=7, decimal_places=2, \
                                blank=True, null=True)
    water_sewer             = models.DecimalField(max_digits=7, decimal_places=2, \
                                blank=True, null=True)
    hoa                     = models.DecimalField(max_digits=7, decimal_places=2, \
                                blank=True, null=True)
    garbage                 = models.DecimalField(max_digits=7, decimal_places=2, \
                                blank=True, null=True)
    pmi                     = models.DecimalField(max_digits=7, decimal_places=2, \
                                blank=True, null=True)
    other_monthly_expenses  = models.DecimalField(max_digits=7, decimal_places=2, \
                                blank=True, null=True)
    annual_expenses_growth  = models.DecimalField(max_digits=4, decimal_places=2, \
                                blank=True, null=True, default=2)
    sales_expenses          = models.DecimalField(max_digits=4, decimal_places=2, \
                                blank=True, null=True, default=7.5)

    def __str__(self):
        """Return a string representation of the model"""
        return self.report_title + ' - ' + self.owner.username + f' ({str(self.id)})'

    def save(self, *args, **kwargs):
        """Saves model. Sets ARV equal to purchase price if ARV is blank"""
        if self.after_repair_value == None:
            self.after_repair_value = self.purchase_price
        super(RentalPropCalcReport, self).save(*args, **kwargs)

calculator/forms.py
# Django imports
from django import forms
from django.forms import widgets

# My file imports
from .models import *

class RentalPropForm(forms.ModelForm):
    """Form for rental property calculator"""
    required_css_class = 'required'
    class Meta:
        model = RentalPropCalcReport
        fields = '__all__'
        widgets = {'owner': forms.HiddenInput()}


class UserSettingsForm(forms.ModelForm):
    """Form for user settings"""
    class Meta:
        model = UserSettings
        fields = '__all__'
        widgets = {'user': forms.HiddenInput()}

calculator/templates/calculator/base.html
{% load static %}
<!doctype html>
<html lang ="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Rental Property Calculator</title>

  {# favicon #}

  {# Global stylesheets #}
  <!-- google fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com"> 
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> 
  <link href="https://fonts.googleapis.com/css2?family=Lato:wght@700&display=swap" rel="stylesheet">

  <!-- bootstrap 5.0 css -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'calculator/styles.css' %}">

  {% block extra_css %}
      {# Override this in templates to add extra stylesheets #}
  {% endblock %}

</head>

<body class="d-flex flex-column min-vh-100 bg-light" data-bs-spy="scroll" data-bs-target="#scroll-list" data-bs-offset="200" tabindex="0">

  <!--Navbar features-->
  <nav class="navbar navbar-expand-lg bg-dark">
    <div class="container-fluid">
      {% comment %} <a class="navbar-brand" href="/">Rise</a> {% endcomment %}
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navButton" aria-controls="navButton" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navButton">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'calculator:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'calculator:rental-prop-calculator' %}">Rental Calculator</a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a role="button" class="nav-link text-white me-2 dropdown-toggle" href="#" data-bs-toggle="dropdown">Hello, {{ user.username }}</a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'calculator:dashboard' %}">Dashboard</a></li>
              <li><a class="dropdown-item" href="{% url 'calculator:reports' %}">Reports</a></li>
              {% if user.is_superuser %}
                <li><a class="dropdown-item" href="{% url 'bot:bot-reports' %}">Bot Reports</a></li>
              {% endif %}
              <li><a class="dropdown-item" href="{% url 'calculator:settings' %}">Settings</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a role="button" class="btn btn-link nav-link text-white" href="{% url 'users:logout' %}">Log out</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a role="button" class="btn btn-link nav-link text-white me-2" href="{% url 'users:register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a role="button" class="btn btn-link nav-link text-white" href="{% url 'users:login' %}">Log in</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  {% block home_image %}{% endblock %}

  <!--Page header features-->
  <main role="main" class="container flex-fill">
    <div >
        {% block page_header %}{% endblock page_header %}
    </div>

    <!--Main content section-->
    <div >
      {% block content %}{% endblock content %}
    </div>
  </main>

  {% comment %} <footer class="footer" id="footer">
    <div class="footer-sections d-flex jutify-content-center text-light py-3">
      <div class="footer-section mx-auto">
        <h4>Explore</h4>
        <ul>
          <li>
            <a href="">Link</a>
          </li>
          <li>
            <a href="">Link</a>
          </li>
          <li>
            <a href="">Link</a>
          </li>
        </ul>
      </div>
      <div class="footer-section mx-auto">
        <h4>Company</h4>
        <ul>
          <li>
            <a href="">Link</a>
          </li>
          <li>
            <a href="">Link</a>
          </li>
          <li>
            <a href="">Link</a>
          </li>
        </ul>
      </div>
    </div>
    <div class="footer-sitename d-flex jutify-content-center bg-dark text-light py-3">
      <div class="mx-auto">
        <span class="copyright">© 2021 Rise, LLC.</span>
        <span class="rights-reserved">All Rights Reserved.</span>
        
      </div>
      
      
    </div>
    
  </footer> {% endcomment %}

  {# Global scripts #}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <script src="{% static 'calculator/script.js' %}"></script>
  
  
  {% block extra_js %}
      {# Override this in templates to add extra stylesheets #}
  {% endblock %}

</body>

</html>

calculator/templates/calculator/settings.html
{% extends "calculator/base.html" %} 
{% load tz %} 
{% load humanize %} 
{% load static %} 
{% load widget_tweaks %}


{% block page_header %}
<div>
  <h1 class="pageTitle text-center py-4">Settings</h1>
</div>

{% endblock page_header %} {% block content %}
<div class="row mx-auto border-top mb-5">
    <div class="col-4">
        <div class="settingsList bg-light list-group rounded-0 border-0 sticky-top justify-content-center mt-5 fs-5" id="scroll-list">
            <a href="#list-item-1" class="w-75 bg-light list-group-item list-group-item-action text-start border-0 rounded">Calculator</a>
            <a href="#list-item-2" class="w-75 bg-light list-group-item list-group-item-action text-start border-0 rounded">Investment Quality</a>
            {% if user.is_superuser %}
                <a href="#list-item-3" class="w-75 bg-light list-group-item list-group-item-action text-start border-0 rounded">Bot</a>
            {% endif %}
            <a href="#list-item-4" class="w-75 bg-light list-group-item list-group-item-action text-start border-0 rounded">Other</a>
        </div>
    </div>

  <div class="col-8 border-start ps-4">
    <form
      class="settingsForm needs-validation"
      method="post"
      enctype="multipart/form-data"
      novalidate
    >
      {% csrf_token %}
    <!-- Calculator Settings -->

      <h3 class="sectionHeading pt-5" id="list-item-1">Calculator Settings</h3>
      <small class="text-muted">*These settings will be used to pre-fill rental calculator fields
      and be used as the default values for running automatic rental reports with the bot.
      </small>


      <h5 class="pt-4">Purchase Info</h5>

      
      <div class="row pt-3">
        <div class="col-4">
          <label class="form-label" for="id_down_payment"
            >Down Payment</label
          >
          {{ form.down_payment|add_class:"form-control" }}
        </div>
      </div>

        <div class="row">
            <div class="col-4 percentage">
                <label class="form-labe" for="id_loan_int_rate"
                    >Interest Rate
                </label>
                {{ form.loan_int_rate|add_class:"form-control" }}
            </div>
        </div>

        <div class="row">
            <div class="col-4">
                <label class="form-label" for="id_loan_term"
                    >Loan Term
                </label>
                {{ form.loan_term|add_class:"form-control" }}
            </div>
        </div>

        <h5 class="pt-3 pb-3">Expenses</h5>

        <div class="row">
            <div class="col-4 percentage">
                <label class="form-label" for="id_repairs_maint"
                    >Repairs/Maint.
                </label>
                {{ form.repairs_maint|add_class:"form-control" }}
            </div>
        </div>

        <div class="row">
            <div class="col-4 percentage">
                <label class="form-label" for="id_vacancy"
                    >Vacancy
                </label>
                {{ form.vacancy|add_class:"form-control" }}
            </div>
        </div>

        <div class="row">
            <div class="col-4 percentage">
                <label class="form-label" for="id_cap_expenditures"
                    >Capital Expenditures
                </label>
                {{ form.cap_expenditures|add_class:"form-control" }}
            </div>
        </div>

        <div class="row">
            <div class="col-4 percentage">
                <label class="form-label" for="id_mgmt_fees"
                    >Management Fees
                </label>
                {{ form.mgmt_fees|add_class:"form-control" }}
            </div>
        </div>

        <h3 class="sectionHeading pt-5" id="list-item-2">Investment Quality Settings</h3>
        <small class="text-muted">*These settings will be used to determine the
        quality of the investment you are looking for. Results will be categorized
        as good(&#128077), average(&#129335), or bad(&#128078) on reports.<br><br>
        "Bad" categorizations will be made for all 
        reports that return a number equal to or lower than what you enter under "Bad Investment".<br>
        "Good" categorizations will be made for all 
        reports that return a number equal to or greater than what you enter under "Good Investment".<br><br>
        *Cash on Cash ROI and Cashflow criteria may be used individually to 
        determine investment quailty. If both criteria are specified, a report 
        will need to meet both good or bad criteria categories to be considered 
        for that designation. Otherwise, if only one criteria is met, the investment
        is considered average.
        </small>

        <h5 class="pt-3 pb-3">Cash on Cash ROI</h5>
        <small class="text-muted">*Leave a spread between your designations so that 
        "average" designations may be made
        </small><br><br>

        <div class="row">
            <div class="col-4 percentage">
                <label class="form-label" for="id_coc_roi_bottom"
                    >Bad Investment
                </label>
                {{ form.coc_roi_bottom|add_class:"form-control" }}
            </div>
            <div class="col-4 percentage">
                <label class="form-label" for="id_coc_roi_top"
                    >Good Investment
                </label>
                {{ form.coc_roi_top|add_class:"form-control" }}
            </div>
        </div>

        <h5 class="pt-3 pb-3">Cashflow</h5>
        <small class="text-muted">*Leave a spread between your designations so that 
        "average" designations may be made
        </small><br><br>

        <div class="row">
            <div class="col-4 currency">
                <label class="form-label" for="id_cashflow_bottom"
                    >Bad Investment
                </label>
                {{ form.cashflow_bottom|add_class:"form-control" }}
            </div>
            <div class="col-4 currency">
                <label class="form-label" for="id_cashflow_top"
                    >Good Investment
                </label>
                {{ form.cashflow_top|add_class:"form-control" }}
            </div>
        </div>

        {% if user.is_superuser %}

            <h3 class="sectionHeading pt-5" id="list-item-3">Bot Settings</h3>
            <small class="text-muted">*These settings will be used to determine the 
            search criteria for the bot so that it can get relevant property data for you. 
            Make sure to read the help sections so you enter the right data for the bot to consume.
            </small>

            <h5 class="pt-3 pb-3">Search area</h5>


            <div class="toggleCityZip">
                <div class="btn-group pb-2" role="group">
                    <input type="radio" class="btn-check" name="btnradio" id="cityradio1" autocomplete="off" checked>
                    <label class="btn btn-outline-primary" for="cityradio1">City</label>

                    <input type="radio" class="btn-check" name="btnradio" id="zipradio2" autocomplete="off">
                    <label class="btn btn-outline-primary" for="zipradio2">Zipcode</label>
                </div>
                <div class="city">
                    <div class="row">
                        <div class="col-6">
                            <label class="form-label" for="id_city"
                                >City Name
                            </label>
                            {{ form.city|add_class:"form-control" }}
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-4">
                            <label class="form-label" for="id_state"
                                >State
                            </label>
                            {{ form.state|add_class:"form-control" }}
                        </div>
                    </div>

                    

                    <div class="row">
                        <div class="col-4">
                            <label class="form-label" for="id_city_code"
                                >City Code
                            </label>
                            {{ form.city_code|add_class:"form-control" }}
                        </div>
                    </div>

                    <div class="row">
                        <div class="col">
                            {{ form.minor_civil_div }}
                            <label for="id_minor_civil_div" id="minor_civil_div"></label>
                        </div>
                    </div>
                </div>

                <div class="zipcode">
                    <div class="row">
                        <div class="col-4">
                            <label class="form-label" for="id_zipcode"
                                >Zipcode
                            </label>
                            {{ form.zipcode|add_class:"form-control" }}
                        </div>
                    </div>
                </div> 
            </div>
            

            <h5 class=" pb-3">Search Filters</h5>

            <div class="row">
                <div class="col-4">
                    <label class="form-label" for="id_min_price"
                        >Min Price
                    </label>
                    {{ form.min_price|add_class:"form-control" }}
                </div>
                <div class="col-4">
                    <label class="form-label" for="id_max_price"
                        >Max Price
                    </label>
                    {{ form.max_price|add_class:"form-control" }}
                </div>
            </div>

            <div class="row">
                <label class="form-label" for="id_prop_type"
                    >Property Type:
                </label>
                {% for checkbox in form.prop_type %}
                    <div class="col-md-12 m2m">
                        <label>{{ checkbox.tag }} {{ checkbox.choice_label }}</label>
                    </div>
                {% endfor %}
            </div>

            <div class="row">
                <div class="col-4">
                    <label class="form-label" for="id_min_beds"
                        >Min Beds
                    </label>
                    {{ form.min_beds|add_class:"form-control" }}
                </div>
                <div class="col-4">
                    <label class="form-label" for="id_max_beds"
                        >Max Beds
                    </label>
                    {{ form.max_beds|add_class:"form-control" }}
                </div>
            </div>

            <div class="row">
                <div class="col-4">
                    <label class="form-label" for="id_min_baths"
                        >Baths
                    </label>
                    {{ form.min_baths|add_class:"form-control" }}
                </div>
            </div>

            {% if item.user.is_superuser %}
                <h5 class="pt-3 pb-3">Auto Search Frequency</h5>

                <div class="row">
                    <div class="col-4">
                        <label class="form-label" for="id_bot_frequency"
                            >Frequency
                        </label>
                        {{ form.bot_frequency|add_class:"form-control" }}
                    </div>
                </div>

                <div class="row">
                    <div class="col-12">
                        <small class="text-muted">*Make sure any updated settings are saved before running the bot!
                        </small><br>
                        {% comment %} <a class="btn btn-primary formattedButton mt-3" href="{% url 'bot:run-bot' %}" role="button">Run Bot</a> {% endcomment %}
                    </div>
                </div>

            {% else %}
                <div class="row">
                    <div class="col-12">
                        <small class="text-muted">*Make sure any updated settings are saved before running the bot!
                        </small><br>
                        {% comment %} <a class="btn btn-primary formattedButton mt-3" href="{% url 'bot:run-bot' %}" role="button">Run Bot</a> {% endcomment %}
                    </div>
                </div>
            {% endif %}

        {% endif %}

        <h3 class="sectionHeading pt-5" id="list-item-4">Other Settings</h3>

        <h5 class="pt-4">Blacklist Settings</h5>

      
        <div class="row">
            <div class="col">
                {{ form.blacklist_bool }}
                <label for="id_blacklist_bool" id="blacklist_bool"></label>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <label class="form-label" for="id_addr_blacklist"
                    >Blacklisted Addresses
                </label>
                {{ form.addr_blacklist|add_class:"form-control" }}
            </div>
        </div>
        

        <div class="row">
            <div class="col">
            {{ form.user }}
            </div>
        </div>

      <div class="settingsButton d-flex justify-content-end pt-5">
        <button type="submit" name="submit" class="btn text-light my-3">Save Settings</button>
      </div>

    </form>
  </div>
</div>
{% endblock content %}